/*
 *                         OpenSplice DDS
 *
 *   This software and documentation are Copyright 2006 to 2015 PrismTech
 *   Limited and its licensees. All rights reserved. See file:
 *
 *                     $OSPL_HOME/LICENSE
 *
 *   for full copyright notice and license terms.
 *
 */
#ifndef IDL_GENLITEHELPER_H
#define IDL_GENLITEHELPER_H

#include "c_typebase.h"

#include "idl_scope.h"
#include "idl_program.h"

#define IDL_GEN_PRINT_LINES 1

#ifdef IDL_GEN_PRINT_LINES
#define IDL_PRINTLINE(i)\
    idl_printIndent (i);\
    idl_fileOutPrintf (idl_fileCur(), "    /* Code generated by %s at line %d */\n",__FILE__,__LINE__);
#else
#define IDL_PRINTLINE(i)
#endif


const char *
idl_getLiteBasicTypeName(
    idl_typeBasic typeBasic);

const c_char *
idl_scopedLiteSequenceBasicTypeName (
    const idl_typeBasic typeBasic);

c_char *
idl_scopedLiteTypeName (
    const idl_typeSpec typeSpec);

#endif /* IDL_GENLITEHELPER_H */
