
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer idl_base_yy_create_buffer
#define yy_delete_buffer idl_base_yy_delete_buffer
#define yy_flex_debug idl_base_yy_flex_debug
#define yy_init_buffer idl_base_yy_init_buffer
#define yy_flush_buffer idl_base_yy_flush_buffer
#define yy_load_buffer_state idl_base_yy_load_buffer_state
#define yy_switch_to_buffer idl_base_yy_switch_to_buffer
#define yyin idl_base_yyin
#define yyleng idl_base_yyleng
#define yylex idl_base_yylex
#define yylineno idl_base_yylineno
#define yyout idl_base_yyout
#define yyrestart idl_base_yyrestart
#define yytext idl_base_yytext
#define yywrap idl_base_yywrap
#define yyalloc idl_base_yyalloc
#define yyrealloc idl_base_yyrealloc
#define yyfree idl_base_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE idl_base_yyrestart(idl_base_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int idl_base_yyleng;

extern FILE *idl_base_yyin, *idl_base_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up idl_base_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up idl_base_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via idl_base_yyrestart()), so that the user can continue scanning by
	 * just pointing idl_base_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when idl_base_yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int idl_base_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow idl_base_yywrap()'s to do buffer switches
 * instead of setting up a fresh idl_base_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void idl_base_yyrestart (FILE *input_file  );
void idl_base_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE idl_base_yy_create_buffer (FILE *file,int size  );
void idl_base_yy_delete_buffer (YY_BUFFER_STATE b  );
void idl_base_yy_flush_buffer (YY_BUFFER_STATE b  );
void idl_base_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void idl_base_yypop_buffer_state (void );

static void idl_base_yyensure_buffer_stack (void );
static void idl_base_yy_load_buffer_state (void );
static void idl_base_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER idl_base_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE idl_base_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE idl_base_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE idl_base_yy_scan_bytes (yyconst char *bytes,int len  );

void *idl_base_yyalloc (yy_size_t  );
void *idl_base_yyrealloc (void *,yy_size_t  );
void idl_base_yyfree (void *  );

#define yy_new_buffer idl_base_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        idl_base_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            idl_base_yy_create_buffer(idl_base_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        idl_base_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            idl_base_yy_create_buffer(idl_base_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define idl_base_yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *idl_base_yyin = (FILE *) 0, *idl_base_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int idl_base_yylineno;

int idl_base_yylineno = 1;

extern char *idl_base_yytext;
#define yytext_ptr idl_base_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up idl_base_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	idl_base_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[105] =
    {   0,
        0,    0,    2,    2,   55,   53,    6,    7,   53,   53,
       28,   21,   53,   15,   16,   26,   24,   17,   25,   53,
       27,   48,   47,   14,   10,   30,   18,   31,   35,   52,
       32,   33,   20,   12,   19,   11,   29,    2,    4,    3,
        0,   51,    0,    0,    9,    0,    0,   41,    1,    0,
       40,   48,    0,   43,    0,   49,   47,   13,   23,   22,
        0,   52,    2,    3,    3,    5,    0,    0,   50,    0,
        0,   45,    0,    0,    8,   36,   39,   44,    0,    0,
       38,   49,    0,    0,    0,    0,    0,    0,   42,   46,
        0,   37,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   34,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   30,   31,   29,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   33,   32,   32,
       34,   35,   36,   37,   32,    1,   38,   39,   29,   40,

       41,   39,   32,   32,   42,   32,   32,   32,   32,   43,
       44,   32,   32,   45,   32,   46,   32,   45,   32,   47,
       32,   32,   48,   49,   50,   51,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[52] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    1,    5,    1,
        1,    6,    1,    1,    1,    1,    1,    7,    7,    8,
        1,    1,    1,    1,    1,    4,    1,    8,    8,    8,
        8,    9,   10,    1,    4,    1,    1,    7,    7,    8,
        8,    9,   10,    9,   10,   10,   10,    1,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[119] =
    {   0,
        0,    0,   49,   50,  196,  321,  321,  321,   49,  192,
      321,  321,  159,  321,  321,  321,  321,  321,  321,   37,
       46,   69,  101,  172,  321,  160,  321,  157,  141,    0,
      321,  321,  321,  321,  321,  321,  321,    0,  321,   47,
       55,  321,   47,  155,  321,  148,   49,   73,  321,   68,
      104,   36,   54,  321,  133,    0,    0,  321,  321,  321,
      112,    0,    0,   58,   62,  321,   93,    0,  321,   88,
        0,  321,  141,  144,  321,  137,  144,  321,  152,   58,
      107,    0,   94,  131,  181,  120,  124,  158,  161,  321,
      169,  172,   86,  138,  163,  109,   69,   70,   59,   59,

       42,   38,  321,  321,  222,  232,  242,  252,  256,  266,
      276,  283,  290,  300,  304,  306,  308,  312
    } ;

static yyconst flex_int16_t yy_def[119] =
    {   0,
      104,    1,  105,  105,  104,  104,  104,  104,  106,  107,
      104,  104,  108,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  109,
      104,  104,  104,  104,  104,  104,  104,  110,  104,  111,
      106,  104,  112,  107,  104,  104,  113,  104,  104,  114,
      104,   22,   52,  104,  104,  115,   23,  104,  104,  104,
      104,  109,  110,  111,  111,  104,  106,  116,  104,  104,
      117,  104,  104,  114,  104,  114,  104,  104,  104,  104,
      104,  115,  104,  106,  106,  104,  118,  104,  104,  104,
      104,  104,  104,  106,  106,  104,  104,  104,  104,  104,

      104,  104,  104,    0,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104
    } ;

static yyconst flex_int16_t yy_nxt[373] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   23,
       24,   25,   26,   27,   28,    6,   29,   30,   30,   30,
       30,   30,   30,   31,    6,   32,   33,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   34,   35,   36,
       37,   39,   39,   42,   48,   48,   48,   49,   65,   42,
       40,   40,   50,   66,   67,   67,   70,   70,  104,  104,
       75,   53,   53,   65,  104,   81,   81,   81,   66,   68,
      103,   71,  104,   43,   51,  102,   52,   52,   53,   43,
       48,   48,   48,   68,   76,   71,   69,   42,   54,   55,

      101,   56,   72,   73,  100,   86,   86,   99,   54,   55,
       84,   84,   72,   73,   98,   56,   51,   69,   57,   57,
       57,   77,   77,   77,   81,   81,   81,   43,   69,   97,
       54,   55,   69,   78,   79,   42,   93,   46,   46,   75,
       54,   55,   42,   78,   79,   80,   75,   80,   94,   94,
       81,   81,   81,   88,   83,   88,   69,   45,   89,   89,
       89,   77,   77,   77,   91,   43,   91,   42,   61,   92,
       92,   92,   43,   90,   79,   89,   89,   89,   89,   89,
       89,   60,   59,   90,   79,   42,   92,   92,   92,   92,
       92,   92,   58,   47,   45,  104,  104,   43,   95,   95,

       95,  104,  104,  104,  104,  104,  104,  104,   95,   95,
       95,   95,  104,  104,  104,   43,  104,  104,   95,   95,
       95,   95,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   41,  104,  104,   41,   41,   41,   41,   41,
       41,   41,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   46,  104,  104,   46,  104,   46,   46,   46,
       46,   46,   62,   62,   62,   62,   63,   63,  104,   63,
       63,  104,   63,   63,   63,   63,   64,   64,  104,   64,
       64,   64,   64,   64,   64,   64,   41,   41,  104,   41,
      104,  104,   41,   46,   46,  104,   46,  104,  104,   46,

       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       82,   82,   85,   85,   87,   87,   96,  104,   96,   96,
        5,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104
    } ;

static yyconst flex_int16_t yy_chk[373] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    9,   20,   20,   20,   21,   40,   41,
        3,    4,   21,   40,   43,   43,   47,   47,   52,   64,
       50,   53,   53,   65,   64,   80,   80,   80,   65,   43,
      102,   47,   52,    9,   22,  101,   22,   22,   22,   41,
       48,   48,   48,   43,   50,   47,   70,   67,   22,   22,

      100,   22,   48,   48,   99,   70,   70,   98,   22,   22,
       67,   67,   48,   48,   97,   22,   23,   96,   23,   23,
       23,   51,   51,   51,   81,   81,   81,   67,   86,   93,
       23,   23,   87,   51,   51,   84,   83,   86,   86,   76,
       23,   23,   94,   51,   51,   55,   74,   55,   84,   84,
       55,   55,   55,   73,   61,   73,   46,   44,   73,   73,
       73,   77,   77,   77,   79,   84,   79,   95,   29,   79,
       79,   79,   94,   77,   77,   88,   88,   88,   89,   89,
       89,   28,   26,   77,   77,   85,   91,   91,   91,   92,
       92,   92,   24,   13,   10,    5,    0,   95,   85,   85,

       85,    0,    0,    0,    0,    0,    0,    0,   85,   85,
       85,   85,    0,    0,    0,   85,    0,    0,   85,   85,
       85,   85,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  106,    0,    0,  106,  106,  106,  106,  106,
      106,  106,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  108,    0,    0,  108,    0,  108,  108,  108,
      108,  108,  109,  109,  109,  109,  110,  110,    0,  110,
      110,    0,  110,  110,  110,  110,  111,  111,    0,  111,
      111,  111,  111,  111,  111,  111,  112,  112,    0,  112,
        0,    0,  112,  113,  113,    0,  113,    0,    0,  113,

      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      115,  115,  116,  116,  117,  117,  118,    0,  118,  118,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int idl_base_yy_flex_debug;
int idl_base_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *idl_base_yytext;
#line 1 "idl_base.l"

#line 3 "idl_base.l"
/**********************************************************************
 *
 * include-statements
 *
 **********************************************************************/
#include <os_heap.h>
#include <os_stdlib.h>
#include <os_errno.h>
#include <ctype.h>
#include <c_stringSupport.h>

#include "idl_genLanguageHelper.h"

/**********************************************************************
 *
 * local macro definitions
 *
 **********************************************************************/

#define pc() parser_column+=strlen(idl_base_yytext)
#define pl() parser_line++; parser_column=0

/**********************************************************************
 *
 * static function prototypes
 *
 **********************************************************************/

static int compareStrings(const char *String1, const char *String2);
static int extractToken(const char *_String);
static os_size_t extractIdent(char *str);
static os_size_t extractString(char *str);
static void preprocessor_directive(char *str);

/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/
/*--------------------------------------------------------------------------*/
#line 639 "<stdout>"

#define INITIAL 0
#define comment 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int idl_base_yylex_destroy (void );

int idl_base_yyget_debug (void );

void idl_base_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE idl_base_yyget_extra (void );

void idl_base_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *idl_base_yyget_in (void );

void idl_base_yyset_in  (FILE * in_str  );

FILE *idl_base_yyget_out (void );

void idl_base_yyset_out  (FILE * out_str  );

int idl_base_yyget_leng (void );

char *idl_base_yyget_text (void );

int idl_base_yyget_lineno (void );

void idl_base_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int idl_base_yywrap (void );
#else
extern int idl_base_yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( idl_base_yytext, idl_base_yyleng, 1, idl_base_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( idl_base_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( idl_base_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, idl_base_yyin))==0 && ferror(idl_base_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(idl_base_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int idl_base_yylex (void);

#define YY_DECL int idl_base_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after idl_base_yytext and idl_base_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 73 "idl_base.l"


#line 830 "<stdout>"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! idl_base_yyin )
			idl_base_yyin = stdin;

		if ( ! idl_base_yyout )
			idl_base_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			idl_base_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				idl_base_yy_create_buffer(idl_base_yyin,YY_BUF_SIZE );
		}

		idl_base_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of idl_base_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 105 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 321 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 75 "idl_base.l"
BEGIN(comment);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 77 "idl_base.l"

	YY_BREAK
case 3:
YY_RULE_SETUP
#line 78 "idl_base.l"

	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 79 "idl_base.l"
{ pl(); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 80 "idl_base.l"
BEGIN(INITIAL);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 82 "idl_base.l"
{ pc(); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 83 "idl_base.l"
{ pl(); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 84 "idl_base.l"
{ pl(); }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 85 "idl_base.l"
{ pl();
                          preprocessor_directive( idl_base_yytext );
                        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 89 "idl_base.l"
{ pc();return IDLTOK_SEMI; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 90 "idl_base.l"
{ pc();return IDLTOK_RPAR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "idl_base.l"
{ pc();return IDLTOK_LPAR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 92 "idl_base.l"
{ pc();return IDLTOK_DOUBLE_COLON; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 93 "idl_base.l"
{ pc();return IDLTOK_COLON; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 94 "idl_base.l"
{ pc();return IDLTOK_LRPAR; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 95 "idl_base.l"
{ pc();return IDLTOK_RRPAR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 96 "idl_base.l"
{ pc();return IDLTOK_COMMA; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 97 "idl_base.l"
{ pc();return IDLTOK_EQUAL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 98 "idl_base.l"
{ pc();return IDLTOK_VERT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 99 "idl_base.l"
{ pc(); return IDLTOK_HAT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 100 "idl_base.l"
{ pc(); return IDLTOK_AMPER; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 101 "idl_base.l"
{ pc(); return IDLTOK_DOUBLE_RIGHT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 102 "idl_base.l"
{ pc(); return IDLTOK_DOUBLE_LEFT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 103 "idl_base.l"
{ pc(); return IDLTOK_PLUS; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 104 "idl_base.l"
{ pc(); return IDLTOK_MINUS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 105 "idl_base.l"
{ pc(); return IDLTOK_TIMES; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 106 "idl_base.l"
{ pc(); return IDLTOK_SLASH; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 107 "idl_base.l"
{ pc(); return IDLTOK_PERCENT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 108 "idl_base.l"
{ pc(); return IDLTOK_TILDE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 109 "idl_base.l"
{ pc(); return IDLTOK_LEFT; } 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 110 "idl_base.l"
{ pc(); return IDLTOK_RIGHT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 111 "idl_base.l"
{ pc(); return IDLTOK_LEPAR; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 112 "idl_base.l"
{ pc(); return IDLTOK_REPAR; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 114 "idl_base.l"
{ pc(); return IDLTOK_ANNOTATION; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 115 "idl_base.l"
{ pc(); return IDLTOK_AT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 116 "idl_base.l"
{ pc(); return IDLTOK_AT_POST; }
	YY_BREAK
case 37:
#line 119 "idl_base.l"
case 38:
#line 120 "idl_base.l"
case 39:
#line 121 "idl_base.l"
case 40:
#line 122 "idl_base.l"
case 41:
#line 123 "idl_base.l"
case 42:
YY_RULE_SETUP
#line 123 "idl_base.l"
{ yylval.Float = (double)atof(idl_base_yytext);
                          pc();return FloatingPtLiteral;
                        }
	YY_BREAK
case 43:
#line 127 "idl_base.l"
case 44:
#line 128 "idl_base.l"
case 45:
#line 129 "idl_base.l"
case 46:
YY_RULE_SETUP
#line 129 "idl_base.l"
{ pc();return FixedPtLiteral;
                        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 131 "idl_base.l"
{ unsigned long long uintValue;
                          sscanf (idl_base_yytext, "%llu", &uintValue);
                          yylval.Integer = (c_longlong) uintValue;
                          pc();return IntegerLiteral;
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 136 "idl_base.l"
{ unsigned long long uintValue;
                          sscanf(idl_base_yytext,"%llo",&uintValue);
                          yylval.Integer = (c_longlong) uintValue;
                          pc();return IntegerLiteral;
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 141 "idl_base.l"
{ unsigned long long uintValue;
                          sscanf(idl_base_yytext,"%llx",&uintValue);
                          yylval.Integer = (c_longlong) uintValue;
                          pc();return IntegerLiteral;
                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 147 "idl_base.l"
{
                         char *str = &idl_base_yytext[1];
                         if (*str == '\\') {
                           switch (*++str) {
                            case 'n': yylval.Char = '\n'; break;
                            case 't': yylval.Char = '\t'; break;
                            case 'v': yylval.Char = '\v'; break;
                            case 'b': yylval.Char = '\b'; break;
                            case 'r': yylval.Char = '\r'; break;
                            case 'f': yylval.Char = '\f'; break;
                            case 'a': yylval.Char = '\a'; break;
                            case '\\': yylval.Char = '\\'; break;
                            case '?': yylval.Char = '\?'; break;
                            case '\'': yylval.Char = '\''; break;
                            case '"': yylval.Char = '"'; break;
                            case '0': case '1': case '2': case '3':
                            case '4': case '5': case '6': case '7':
                             yylval.Char = 0;
                              while (*str && *str != '\'') {
                                yylval.Char = yylval.Char * 8 + (*str++ - '0');
                              }
                              break;
                            case 'x':
                            case 'X':
                             yylval.Char = 0;
                              str++;
                              while (*str && *str != '\'') {
                                if (*str >= '0' && *str <= '9')
                                  yylval.Char = yylval.Char * 16 +
                                                       (*str - '0');
                                else if (*str >= 'a' && *str <= 'f')
                                  yylval.Char = yylval.Char * 16 +
                                                       (*str - 'a') + 10;
                                else if (*str >= 'A' && *str <= 'F')
                                  yylval.Char = yylval.Char * 16 +
                                                       (*str - 'f') + 10;
                                str++;
                              }
                              break;
                            }
                          }
                          else {
                             yylval.Char = *str;
                          }
                          pc();return CharacterLiteral;
                        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 193 "idl_base.l"
{ extractString(idl_base_yytext);
                          pc();return StringLiteral;
                        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 196 "idl_base.l"
{ extractIdent(idl_base_yytext);
                          pc();return extractToken(idl_base_yytext);
                        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 200 "idl_base.l"
{
                            pc();
                            return idl_base_yytext[0];
                        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 204 "idl_base.l"
ECHO;
	YY_BREAK
#line 1232 "<stdout>"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed idl_base_yyin at a new source and called
			 * idl_base_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = idl_base_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( idl_base_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * idl_base_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of idl_base_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					idl_base_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			idl_base_yyrestart(idl_base_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) idl_base_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 105 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 105 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 104);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up idl_base_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					idl_base_yyrestart(idl_base_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( idl_base_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve idl_base_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void idl_base_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        idl_base_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            idl_base_yy_create_buffer(idl_base_yyin,YY_BUF_SIZE );
	}

	idl_base_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	idl_base_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void idl_base_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		idl_base_yypop_buffer_state();
	 *		idl_base_yypush_buffer_state(new_buffer);
     */
	idl_base_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	idl_base_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (idl_base_yywrap()) processing, but the only time this flag
	 * is looked at is after idl_base_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void idl_base_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	idl_base_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE idl_base_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) idl_base_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in idl_base_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) idl_base_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in idl_base_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	idl_base_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with idl_base_yy_create_buffer()
 * 
 */
    void idl_base_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		idl_base_yyfree((void *) b->yy_ch_buf  );

	idl_base_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a idl_base_yyrestart() or at EOF.
 */
    static void idl_base_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	idl_base_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then idl_base_yy_init_buffer was _probably_
     * called from idl_base_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void idl_base_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		idl_base_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void idl_base_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	idl_base_yyensure_buffer_stack();

	/* This block is copied from idl_base_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from idl_base_yy_switch_to_buffer. */
	idl_base_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void idl_base_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	idl_base_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		idl_base_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void idl_base_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)idl_base_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in idl_base_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)idl_base_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in idl_base_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE idl_base_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) idl_base_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in idl_base_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	idl_base_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to idl_base_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       idl_base_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE idl_base_yy_scan_string (yyconst char * yystr )
{
    
	return idl_base_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to idl_base_yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE idl_base_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) idl_base_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in idl_base_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = idl_base_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in idl_base_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up idl_base_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		idl_base_yytext[idl_base_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = idl_base_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		idl_base_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int idl_base_yyget_lineno  (void)
{
        
    return idl_base_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *idl_base_yyget_in  (void)
{
        return idl_base_yyin;
}

/** Get the output stream.
 * 
 */
FILE *idl_base_yyget_out  (void)
{
        return idl_base_yyout;
}

/** Get the length of the current token.
 * 
 */
int idl_base_yyget_leng  (void)
{
        return idl_base_yyleng;
}

/** Get the current token.
 * 
 */

char *idl_base_yyget_text  (void)
{
        return idl_base_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void idl_base_yyset_lineno (int  line_number )
{
    
    idl_base_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see idl_base_yy_switch_to_buffer
 */
void idl_base_yyset_in (FILE *  in_str )
{
        idl_base_yyin = in_str ;
}

void idl_base_yyset_out (FILE *  out_str )
{
        idl_base_yyout = out_str ;
}

int idl_base_yyget_debug  (void)
{
        return idl_base_yy_flex_debug;
}

void idl_base_yyset_debug (int  bdebug )
{
        idl_base_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from idl_base_yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    idl_base_yyin = stdin;
    idl_base_yyout = stdout;
#else
    idl_base_yyin = (FILE *) 0;
    idl_base_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * idl_base_yylex_init()
     */
    return 0;
}

/* idl_base_yylex_destroy is for both reentrant and non-reentrant scanners. */
int idl_base_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		idl_base_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		idl_base_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	idl_base_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * idl_base_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *idl_base_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *idl_base_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void idl_base_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see idl_base_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 204 "idl_base.l"



/**********************************************************************
 *
 * static functions
 *
 **********************************************************************/

static int
compareStrings(const char *String1, const char *String2)
{
   return os_strcasecmp(String1, String2);
}

static int
extractToken(const char *_String)
{
   if (!compareStrings(_String, "abstract"    ) ) return IDLTOK_ABSTRACT;
   if (!compareStrings(_String, "any"         ) ) return IDLTOK_ANY;
/* if (!compareStrings(_String, "array"       ) ) return IDLTOK_ARRAY;		*/
   if (!compareStrings(_String, "attribute"   ) ) return IDLTOK_ATTRIBUTE;
/* if (!compareStrings(_String, "bag"         ) ) return IDLTOK_BAG;		*/
   if (!compareStrings(_String, "boolean"     ) ) return IDLTOK_BOOLEAN;
   if (!compareStrings(_String, "case"        ) ) return IDLTOK_CASE;
   if (!compareStrings(_String, "char"        ) ) return IDLTOK_CHAR;
/* if (!compareStrings(_String, "class"       ) ) return IDLTOK_CLASS;		*/
   if (!compareStrings(_String, "component"   ) ) return IDLTOK_COMPONENT;
   if (!compareStrings(_String, "const"       ) ) return IDLTOK_CONST;
   if (!compareStrings(_String, "consumes"    ) ) return IDLTOK_CONSUMES;
   if (!compareStrings(_String, "context"     ) ) return IDLTOK_CONTEXT;
   if (!compareStrings(_String, "custom"      ) ) return IDLTOK_CUSTOM;
/* if (!compareStrings(_String, "date"        ) ) return IDLTOK_DATE;		*/
   if (!compareStrings(_String, "default"     ) ) return IDLTOK_DEFAULT;
/* if (!compareStrings(_String, "dictionary"  ) ) return IDLTOK_DICTIONARY;	*/
   if (!compareStrings(_String, "double"      ) ) return IDLTOK_DOUBLE;
   if (!compareStrings(_String, "emits"       ) ) return IDLTOK_EMITS;
   if (!compareStrings(_String, "enum"        ) ) return IDLTOK_ENUM;
   if (!compareStrings(_String, "eventtype"   ) ) return IDLTOK_EVENTTYPE;
   if (!compareStrings(_String, "exception"   ) ) return IDLTOK_EXCEPTION;
/* if (!compareStrings(_String, "extends"     ) ) return IDLTOK_EXTENDS;	*/
/* if (!compareStrings(_String, "extent"      ) ) return IDLTOK_EXTENT;	*/
   if (!compareStrings(_String, "factory"     ) ) return IDLTOK_FACTORY;
   if (!compareStrings(_String, "FALSE"       ) ) return IDLTOK_FALSE;
   if (!compareStrings(_String, "finder"      ) ) return IDLTOK_FINDER;
   if (!compareStrings(_String, "fixed"       ) ) return IDLTOK_FIXED;
   if (!compareStrings(_String, "float"       ) ) return IDLTOK_FLOAT;
   if (!compareStrings(_String, "getraises"   ) ) return IDLTOK_GETRAISES;
   if (!compareStrings(_String, "home"        ) ) return IDLTOK_HOME;
   if (!compareStrings(_String, "import"      ) ) return IDLTOK_IMPORT;
   if (!compareStrings(_String, "in"          ) ) return IDLTOK_IN;
   if (!compareStrings(_String, "inout"       ) ) return IDLTOK_INOUT;
   if (!compareStrings(_String, "interface"   ) ) return IDLTOK_INTERFACE;
/* if (!compareStrings(_String, "interval"    ) ) return IDLTOK_INTERVAL;	*/
/* if (!compareStrings(_String, "inverse"     ) ) return IDLTOK_INVERSE;	*/
/* if (!compareStrings(_String, "key"         ) ) return IDLTOK_KEY;		*/
/* if (!compareStrings(_String, "keys"        ) ) return IDLTOK_KEYS;		*/
/* if (!compareStrings(_String, "list"        ) ) return IDLTOK_LIST;		*/
   if (!compareStrings(_String, "local"       ) ) return IDLTOK_LOCAL;
   if (!compareStrings(_String, "long"        ) ) return IDLTOK_LONG;
   if (!compareStrings(_String, "manages"     ) ) return IDLTOK_MANAGES;
   if (!compareStrings(_String, "map"         ) ) return IDLTOK_MAP;
   if (!compareStrings(_String, "module"      ) ) return IDLTOK_MODULE;
   if (!compareStrings(_String, "multiple"    ) ) return IDLTOK_MULTIPLE;
   if (!compareStrings(_String, "native"      ) ) return IDLTOK_NATIVE;
   if (!compareStrings(_String, "Object"      ) ) return IDLTOK_OBJECT;
   if (!compareStrings(_String, "octet"       ) ) return IDLTOK_OCTET;
   if (!compareStrings(_String, "oneway"      ) ) return IDLTOK_ONEWAY;
/* if (!compareStrings(_String, "order_by"    ) ) return IDLTOK_ORDER_BY;	*/
   if (!compareStrings(_String, "out"         ) ) return IDLTOK_OUT;
/* if (!compareStrings(_String, "persistent"  ) ) return IDLTOK_PERSISTENT;	*/
   if (!compareStrings(_String, "primarykey"  ) ) return IDLTOK_PRIMARYKEY;
   if (!compareStrings(_String, "private"     ) ) return IDLTOK_PRIVATE;
   if (!compareStrings(_String, "provides"    ) ) return IDLTOK_PROVIDES;
   if (!compareStrings(_String, "public"      ) ) return IDLTOK_PUBLIC;
   if (!compareStrings(_String, "publishes"   ) ) return IDLTOK_PUBLISHES;
   if (!compareStrings(_String, "raises"      ) ) return IDLTOK_RAISES;
   if (!compareStrings(_String, "readonly"    ) ) return IDLTOK_READONLY;
/* if (!compareStrings(_String, "relationship") ) return IDLTOK_RELATIONSHIP;	*/
   if (!compareStrings(_String, "setraises"   ) ) return IDLTOK_SETRAISES;
   if (!compareStrings(_String, "sequence"    ) ) return IDLTOK_SEQUENCE;
/* if (!compareStrings(_String, "set"         ) ) return IDLTOK_SET;		*/
   if (!compareStrings(_String, "short"       ) ) return IDLTOK_SHORT;
   if (!compareStrings(_String, "string"      ) ) return IDLTOK_STRING;
   if (!compareStrings(_String, "struct"      ) ) return IDLTOK_STRUCT;
   if (!compareStrings(_String, "supports"    ) ) return IDLTOK_SUPPORTS;
   if (!compareStrings(_String, "switch"      ) ) return IDLTOK_SWITCH;
/* if (!compareStrings(_String, "time"        ) ) return IDLTOK_TIME;		*/
/* if (!compareStrings(_String, "timestamp"   ) ) return IDLTOK_TIMESTAMP;	*/
/* if (!compareStrings(_String, "transient"   ) ) return IDLTOK_TRANSIENT;	*/
   if (!compareStrings(_String, "TRUE"        ) ) return IDLTOK_TRUE;
   if (!compareStrings(_String, "truncatable" ) ) return IDLTOK_TRUNCATABLE;
   if (!compareStrings(_String, "typedef"     ) ) return IDLTOK_TYPEDEF;
   if (!compareStrings(_String, "typeid"      ) ) return IDLTOK_TYPEID;
   if (!compareStrings(_String, "typeprefix"  ) ) return IDLTOK_TYPEPREFIX;
   if (!compareStrings(_String, "union"       ) ) return IDLTOK_UNION;
   if (!compareStrings(_String, "uses"        ) ) return IDLTOK_USES;
   if (!compareStrings(_String, "unsigned"    ) ) return IDLTOK_UNSIGNED;
   if (!compareStrings(_String, "ValueBase"   ) ) return IDLTOK_VALUEBASE;
   if (!compareStrings(_String, "valuetype"   ) ) return IDLTOK_VALUETYPE;
   if (!compareStrings(_String, "void"        ) ) return IDLTOK_VOID;
   if (!compareStrings(_String, "wchar"       ) ) return IDLTOK_WCHAR;
   if (!compareStrings(_String, "wstring"     ) ) return IDLTOK_WSTRING;

   return Identifier;
}

static os_size_t
extractIdent(char *str)
{
   os_size_t length = strlen(str);
   if (str[0] == '_') {
      /* escaped identifier, remove the preceeding _ */
      length--;
      str++;
   }
   yylval.String = (char*)os_malloc(length+1);
   os_strncpy(yylval.String, str, length);
   yylval.String[length]=0;
   return length;
}

static os_size_t
extractString(char *str)
{
   os_size_t length = strlen(str) - 1;
   yylval.String = (char*)os_malloc(length);
   os_strncpy(yylval.String, ++str, length-1);
   yylval.String[length-1]=0;
   return length;
}

static void
preprocessor_directive(char *str)
{
    int lineNumber;
    os_size_t length;
    char *fileName, *ptr;
    c_iter pragmaItems;
    char *pragmaName, *typeName, *fieldName, *newFieldName;
    char valueString[1000];
    c_metaObject mo;

    str++; /* skip # */
    if (strncmp(str, "pragma", 6) == 0) {
        str += 7;
        pragmaItems = c_splitString(str, " ,\t\r\n");
        pragmaName = c_iterTakeFirst(pragmaItems);
        if (pragmaName && strcmp(pragmaName, "keylist") == 0) {
            typeName = c_iterTakeFirst(pragmaItems);
            if (typeName) {
                if (idl_checkKeyListTypeName(scope, typeName, yyerror) == 0) {
                    mo = c_metaObject(c_metaFindByName (scope, typeName, CQ_METAOBJECTS));
                } else {
                    mo = NULL;
                }
                valueString[0] = '\0';
                if (mo) {
                    while (c_iterLength(pragmaItems)) {
                        fieldName = c_iterTakeFirst(pragmaItems);
                        if (fieldName[0] == '_') { /* escape character, which must be removed */
                            newFieldName = (char *)os_malloc(strlen(fieldName));
                            os_strcpy(newFieldName, &(fieldName[1]));
                            os_free(fieldName);
                            fieldName = newFieldName;
                        }
                        idl_checkKeyListFieldName(mo, fieldName, yyerror);
                        strcat(valueString, fieldName);
                        if (c_iterLength(pragmaItems)) {
                            strcat(valueString, ",");
                        }
                    }
                }
                idl_keyDefAdd (idl_keyDefDefGet(), scope, typeName, valueString);
            }
        } else if(pragmaName && strcmp(pragmaName, "cats") == 0) {
            typeName = c_iterTakeFirst(pragmaItems);
            if (typeName) {
                if (idl_checkKeyListTypeName(scope, typeName, yyerror) == 0) {
                    mo = c_metaObject(c_metaFindByName (scope, typeName, CQ_METAOBJECTS));
                } else {
                    mo = NULL;
                }
                valueString[0] = '\0';
                if (mo) {
                    while (c_iterLength(pragmaItems)) {
                        fieldName = c_iterTakeFirst(pragmaItems);
                        if (fieldName[0] == '_') { /* escape character, which must be removed */
                            newFieldName = (char *)os_malloc(strlen(fieldName));
                            os_strcpy(newFieldName, &(fieldName[1]));
                            os_free(fieldName);
                            fieldName = newFieldName;
                        }
                        idl_checkSimpleFieldName(mo, fieldName, yyerror);
                        strcat(valueString, fieldName);
                        if (c_iterLength(pragmaItems)) {
                            strcat(valueString, ",");
                        }
                    }
                }
                idl_catsDefAdd (idl_catsDefDefGet(), scope, typeName, valueString);
            }
        } else if(pragmaName && strcmp(pragmaName, "stac") == 0) {
            typeName = c_iterTakeFirst(pragmaItems);
            if (typeName) {
                if (idl_checkKeyListTypeName(scope, typeName, yyerror) == 0) {
                    mo = c_metaObject(c_metaFindByName (scope, typeName, CQ_METAOBJECTS));
                } else {
                    mo = NULL;
                }
                valueString[0] = '\0';
                if (mo) {
                    newFieldName = NULL;

                    while (c_iterLength(pragmaItems)) {
                        fieldName = c_iterTakeFirst(pragmaItems);
                        if (fieldName[0] == '_') { /* escape character, which must be removed */
                            newFieldName = (char *)os_malloc(strlen(fieldName));
                            os_strcpy(newFieldName, &(fieldName[1]));
                            os_free(fieldName);
                            fieldName = newFieldName;
                        }
                        idl_checkSimpleFieldName(mo, fieldName, yyerror);
                        strcat(valueString, fieldName);
                        if (c_iterLength(pragmaItems)) {
                            strcat(valueString, ",");
                        }
                        if(newFieldName){
                            os_free(newFieldName);
                            newFieldName = NULL;
                        }
                    }
                }
                idl_stacDefAdd (idl_stacDefDefGet(), scope, typeName, valueString);
            }
        } else if(pragmaName && strcmp(pragmaName, "stream") == 0) {
            typeName = c_iterTakeFirst(pragmaItems);
            if (typeName && (idl_checkKeyListTypeName(scope, typeName, yyerror) == 0)) {
                idl_streamsDefAdd(idl_streamsDefDefGet(), scope, typeName);
            }
        }
        /* Turn off newtypes generation for files generated for isocpp streams */
        else if(pragmaName && strcmp(pragmaName, "isostream") == 0) {
            idl_setIsISOCppStreams(OS_TRUE);
        }
    }
    /* The Visual Studio compiler generates different output */
    if (strncmp (str, "line", 4) == 0) { /* Visual Studio only */
        str = &str[4]; /* Skip the line expression */
    }
    lineNumber = (int) strtol(str,&ptr,10);
    while ((*ptr != 0) && ((*ptr == ' ') || (*ptr == '\t'))) ptr++;
    if (*ptr == '"') {
        ptr++;
        if (*ptr != '<') {
            fileName = ptr;
        } else {
            return;
        }
    } else {
        return;
    }
    while (isprint((int)*ptr) && (*ptr != '"')) ptr++;
    length = (os_size_t) (ptr - fileName);
    if (length >= MAX_FILENAME_LENGTH) {
        fprintf(stderr,"filename <%s> exceeds max length of %d\n",fileName,MAX_FILENAME_LENGTH);
        exit(-1);
    }
    while ((*ptr != 0) && ((*ptr == ' ') || (*ptr == '\t'))) ptr++;
    if (*ptr != '"') return;
    os_strncpy(file_name,fileName,length);
    file_name[length] = 0;
    idl_fileMapAdd(idl_fileMapDefGet(), file_name);
    parser_line = lineNumber;
    parser_column = 0;
}

